### PR TITLE
Support renamed metrics (and fix build_info queries)

### LINKED ISSUE #55: Support renamed metrics
All queries should be updated in the following way:
- Any references to the function call counter should be identified using `{__name__=~"function_calls(_count)?(_total)?"}`
- Any references to the histogram should be identified using `{__name__=~"function_calls_duration(_seconds)?_bucket"}` or `_count`/`_sum`

### PR DESCRIPTION
**Pull request by brettimus**
I hit an issue while testing the 0.5.0 prerelease. I thought it might have to do with the updates in metric names, so I changed those. 

Turns out the issue was with the build_info query. So, I patched that.

Everything's working now for me locally

Fixes #55

### CODE REVIEW

File: src/queries.ts [hunk 1]
```diff
@@ -146,15 +128,16 @@ export function generateLatencyQuery(
...
           function=~"${functionName}",
           module=~"${moduleName || ".*"}"
         }[5m]
       )
       # Attach the "version" and "commit" labels from the "build_info" metric 
       * on (instance, job) group_left(version, commit) (
-        last_over_time(build_info[1s])
-      )
+        last_over_time(build_info[1s]) or on (instance, job) up
+      )
```
Comment (flenter) [inline src/queries.ts:140]: This trailing space isn't needed

**Review by flenter — APPROVED** [review]
👍 looks good to me
